// initial
#define DEFINE_LUA_CLASS(TYPE, CLASS, SUPER_CLASS)

#define DEFINE_LUA_CLASS_BY_PROXY(TYPE, CLASS, SUPER_CLASS)

#define DEFINE_LUA_CLASS_NO_CTOR(TYPE, CLASS, SUPER_CLASS)

#define DEFINE_LUA_CLASS_NO_DTOR(TYPE, CLASS, SUPER_CLASS)

#define DEFINE_LUA_CLASS_NO_CTOR_NO_DTOR(TYPE, CLASS, SUPER_CLASS) 
	
#define DEFINE_LUA_CLASS_PUBLIC_MEMBERS(TYPE, CLASS, SUPER_CLASS) 	

#define DEFINE_LUA_CLASS_PUBLIC_MEMBERS_NODTOR(TYPE, CLASS, SUPER_CLASS) 
	
#define DEFINE_LUA_CLASS_PUBLIC_MEMBERS_NOCTOR_NODTOR(TYPE, CLASS, SUPER_CLASS) 
	
// library
#define DEFINE_LUA_CLASS_LIB(TYPE, CLASS, SUPER_CLASS)

#define DEFINE_LUA_CLASS_LIB_PUBLIC_MEMBERS(TYPE, CLASS, SUPER_CLASS)
	
// PROXY / PUBLIC_MEMBERS / CTOR / DTOR / 
